= Parameters

The parent key for all of the following parameters is `registry_cache`.

== `namespace`

[horizontal]
type:: string
default:: `syn-registry-cache`

The namespace in which to deploy this component.


== `fqdn`

[horizontal]
type:: string
default:: `dockerhub.vshn.net`

FQDN under which the registry will be served


== `expose_type`

[horizontal]
type:: string
default:: `ingress`
possible values:: `ingress` or `route`

Whether to use an `Ingress` or `Route` object to expose the registry.


== `imagePullSecretName`

[horizontal]
type:: string
default:: `registry-pull-secret`

The name of an image pull secret to use, if not null.
The secret is configured for both the Registry and the Redis deployments.


== `imagePullSecret`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
imagePullSecret:
  type: 'kubernetes.io/dockerconfigjson'
  stringData:
    .dockerconfigjson: '?{vaultkv:${cluster:tenant}/${cluster:name}/registry-cache/image_pull_secret}'
----

The image pull secret for pulling from docker.io.

[NOTE]
====
This creates a secret of type `kubernetes.io/dockerconfigjson`.
[source,yaml]
----
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "docker.io": { xxx }
      }
    }
----
====


== `redis`

Configuration of the Redis component.

=== `redis.enabled`

[horizontal]
type:: bool
default:: `true`

Whether or not to deploy and use redis as a Blob descriptor cache.

=== `redis.resources`

[horizontal]
type: dict
default: https://github.com/projectsyn/component-registry-cache/blob/master/class/defaults.yml[See `class/defaults.yml`]

Configure resource requests and limits for Redis component.

[WARNING]
====
Memory limit must be specified in the redis resources limits, as Redis is used as a LRU cache.
====

=== `redis.config`

[horizontal]
type: dict
default: https://github.com/projectsyn/component-registry-cache/blob/master/class/defaults.yml[See `class/defaults.yml`]

Redis configuration.


== `registry`

Configuration of the Registry component.

=== `registry.replicas`

[horizontal]
type: integer
default:: 2

Configures how many replicas of the Registry component to deploy.

=== `registry.config.storage.s3.bucket`, `registry.config.storage.s3.regionendpoint`

[horizontal]
type:: strings
mandatory:: **yes**
example::
+
[source,yaml]
----
s3:
  bucket: example-harbor-instance-data
  endpoint: https://s3.example.com/
----

S3 configuration for the image store

=== `registry.config.storage.s3.accesskey`, `registry.config.storage.s3.secretkey`

[horizontal]
type:: strings
default:: Vault reference

S3 credentials for storing image blobs.


== `http_secret`

[horizontal]
type:: string
default:: Vault reference

HTTP Session secret. Must be set but is only used internally.


== Vault secrets

[source,bash]
----
# Adjust to your environment
key="clusters/kv/${TENANT_ID}/${CLUSTER_ID}/registry-cache"

# Query for existing secrets first
vault kv get "${key}"

# If there are existing secrets, add your instance secrets:
vault kv patch "${key}" \
  http_secret=$(pwgen 32 1) \
  proxy_username=DOCKER_HUB_USERNAME \
  proxy_password=DOCKER_HUB_PASSWORD \
  s3_accesskey=S3_ACCESS_KEY \
  s3_secretkey=S3_SECRET_KEY

# If there is no pre-existing secret, create new:
vault kv put "${key}" \
  http_secret=$(pwgen 32 1) \
  proxy_username=DOCKER_HUB_USERNAME \
  proxy_password=DOCKER_HUB_PASSWORD \
  s3_accesskey=S3_ACCESS_KEY \
  s3_secretkey=S3_SECRET_KEY
----
